name: Build Windows Portable

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Application
        run: flutter build windows --release

      - name: Compress Release Archive
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\x64\release\runner\* -DestinationPath dev_tools_windows_portable.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev_tools_windows_portable
          path: dev_tools_windows_portable.zip
